apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lattice
resources:
  - kafka.yaml
  - redis.yaml
  - observability.yaml
  - operations.yaml
  - rbac.yaml
  - default-deny.yaml
  - networkpolicy.yaml
  - query.yaml
  - indexer.yaml
