apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lattice-secure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nickemma/lattice.git
    targetRevision: main
    path: deploy/k8s-secure
  destination:
    server: https://kubernetes.default.svc
    namespace: lattice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Terraform owns the namespace; Argo owns the resources inside it.
      - ApplyOutOfSyncOnly=true
